# Generated by Django 4.2.7 on 2023-12-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_student_father_nmae'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentmodel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('father_nmae', models.CharField(default='father', max_length=20)),
            ],
        ),
    ]
